HTML = '''<!doctype html><html lang="pl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mapowanie katalogów</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7f8;color:#20292d;font:14px system-ui}header{background:white;border-bottom:1px solid #ced6db;padding:20px 28px}main{max-width:1160px;margin:auto;padding:28px}h1{font-size:24px}h2{font-size:18px}section{padding:24px 0;border-bottom:1px solid #d5dce0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px 28px}label{display:block;margin-bottom:8px}input,select{width:100%;padding:11px;border:1px solid #bfcbd2;border-radius:6px;background:white;font:inherit}button{padding:11px 18px;border:1px solid #aabac4;background:white;border-radius:6px;cursor:pointer;font:inherit;margin:12px 8px 0 0}button.primary{background:#087c70;color:white;border-color:#087c70}button:disabled{opacity:.5;cursor:default}a{color:#076a98}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:12px;border-bottom:1px solid #d5dce0;overflow-wrap:anywhere}.table{overflow:auto}#busy{position:fixed;inset:0;background:#fffffff0;display:grid;place-items:center;font-size:20px}#busy[hidden]{display:none}.rule{display:grid;grid-template-columns:1fr 1fr auto;gap:16px;align-items:center;margin:16px 0}.rule button{margin:0}#status{padding:16px 0;color:#8b351a;white-space:pre-wrap}@media(max-width:650px){main{padding:18px}.grid,.rule{grid-template-columns:1fr}th,td{padding:8px}}
</style><header><a href="/transfer">Paczka PIM</a> / Mapowanie katalogów</header><main><h1>Mapowanie katalogów</h1>
<section><div class="grid"><div><label for="data">Dane i definicje modeli (JSON)</label><input id="data" type="file" multiple accept=".json"></div>
<div><label for="module">Rodzaj danych</label><select id="module"><option value="products">Produkty</option><option value="buildingelements">Elementy budowlane</option></select></div>
<div><label for="folder">Katalog dokumentów</label><input id="folder" type="file" webkitdirectory multiple></div>
<div><label for="planFile">Zapisany plan powiązań</label><input id="planFile" type="file" accept=".json"></div></div></section>
<section><h2>Powiązanie z danymi</h2><div class="grid"><div><label for="key">Pole odpowiadające nazwie katalogu</label><select id="key"></select></div>
<div><label for="depth">Poziom katalogu produktu / elementu</label><input id="depth" type="number" min="1" max="20" value="1"></div>
<div><label for="version">Wersja danych</label><select id="version"></select></div><div><label for="attribute">Domyślny atrybut plikowy</label><select id="attribute"></select></div></div>
<h2>Typy dokumentów według podkatalogów</h2><div id="rules"></div><button id="addRule">Dodaj regułę podkatalogu</button><button id="scan" class="primary">Sprawdź powiązania</button></section>
<section><h2 id="summary">Podgląd powiązań</h2><div class="table"><table><thead><tr><th>Plik</th><th>Katalog obiektu</th><th>Typ / podkatalog</th><th>ID obiektu</th><th>Atrybut</th><th>Wynik</th></tr></thead><tbody id="rows"></tbody></table></div>
<button id="save" disabled>Zapisz plan powiązań</button><button id="pack" class="primary" disabled>Odczytaj pliki i przygotuj paczkę</button></section><div id="status" role="status"></div></main><div id="busy" hidden>Analiza danych...</div>
<script>
const el=id=>document.getElementById(id);let result=null,attrs=[];
function invalidate(){result=null;el('save').disabled=true;el('pack').disabled=true;el('rows').replaceChildren();el('summary').textContent='Podgląd wymaga sprawdzenia';}
function settings(){return {module:el('module').value,key:el('key').value,version_id:Number(el('version').value),attribute_id:Number(el('attribute').value),owner_depth:Number(el('depth').value),rules:[...el('rules').children].map(r=>({folder:r.querySelector('input').value,attribute_id:Number(r.querySelector('select').value)}))};}
function files(){return [...el('folder').files].map(file=>({file,path:file.webkitRelativePath.split('/').slice(1).join('/')}));}
function choices(select,values){select.replaceChildren();for(const [value,text] of values){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}}
async function task(fn){el('status').replaceChildren();el('busy').hidden=false;try{await fn();}catch(e){el('status').textContent=e.message;}finally{el('busy').hidden=true;}}
async function request(optionsOnly=false){const fd=new FormData();for(const f of el('data').files)fd.append('data_files',f);fd.append('module',el('module').value);if(!optionsOnly){for(const [k,v] of Object.entries(settings()))if(k!=='module')fd.append(k,k==='rules'?JSON.stringify(v):v);fd.append('paths',JSON.stringify(files().map(f=>f.path)));}const response=await fetch('/transfer/folders',{method:'POST',body:fd});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
async function options(){invalidate();const data=await request(true);attrs=data.attributes;choices(el('key'),data.keys.map(k=>[k,k]));choices(el('version'),data.versions.map(v=>[v,v]));choices(el('attribute'),attrs.map(a=>[a.id,a.name+' [ID '+a.id+']']));el('rules').replaceChildren();}
function addRule(rule={}){const row=document.createElement('div');row.className='rule';const input=document.createElement('input');input.placeholder='np. Deklaracje lub Dokumenty/Karty';input.setAttribute('aria-label','Podkatalog typu dokumentu');input.value=rule.folder||'';const select=document.createElement('select');select.setAttribute('aria-label','Docelowy atrybut plikowy');choices(select,attrs.map(a=>[a.id,a.name+' [ID '+a.id+']']));if(rule.attribute_id)select.value=rule.attribute_id;const remove=document.createElement('button');remove.textContent='Usuń';remove.onclick=()=>{row.remove();invalidate();};row.append(input,select,remove);row.onchange=invalidate;el('rules').append(row);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.textContent='Pobierz '+name;el('status').replaceChildren(a);}
el('data').onchange=()=>task(options);el('module').onchange=()=>task(options);for(const id of ['folder','key','depth','version','attribute'])el(id).onchange=invalidate;
el('addRule').onclick=()=>{addRule();invalidate();};
el('scan').onclick=()=>task(async()=>{invalidate();if(!files().length)throw new Error('Wybierz katalog z plikami');result=await request();el('summary').textContent=`Dopasowano: ${result.matched}. Nierozwiązane: ${result.unresolved}.`;for(const row of result.rows){const tr=document.createElement('tr');for(const k of ['file','folder','document_type','owner_id','attribute_id','status']){const td=document.createElement('td');td.textContent=row[k]??'';tr.append(td);}el('rows').append(tr);}el('save').disabled=false;el('pack').disabled=result.unresolved>0||!result.matched;});
el('save').onclick=()=>{const plan={format:'pim-folder-plan.v1',source_root:el('folder').files[0]?.webkitRelativePath.split('/')[0],settings:settings(),...result};download(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}),'powiazania-plikow.json');};
el('planFile').onchange=()=>task(async()=>{const plan=JSON.parse(await el('planFile').files[0].text());if(plan.format!=='pim-folder-plan.v1')throw new Error('Nieprawidłowy plan');el('module').value=plan.settings.module;await options();const s=plan.settings;for(const [id,key] of [['key','key'],['version','version_id'],['attribute','attribute_id'],['depth','owner_depth']])el(id).value=s[key];for(const rule of s.rules||[])addRule(rule);el('status').textContent='Plan wczytany. Wskaż katalog i sprawdź aktualne powiązania.';});
el('pack').onclick=()=>task(async()=>{if(!result||result.unresolved||!result.matched)throw new Error('Najpierw sprawdź powiązania');const fd=new FormData();for(const f of el('data').files)fd.append('data_files',f);fd.append('links_file',new Blob([JSON.stringify(result.links)],{type:'application/json'}),'links.json');const selected=new Set(result.links.map(l=>l.file));for(const entry of files())if(selected.has(entry.path))fd.append('attachments',entry.file,entry.path);const response=await fetch('/transfer/package',{method:'POST',body:fd});if(!response.ok){const error=await response.json();throw new Error(JSON.stringify(error.detail));}download(await response.blob(),'pim-transfer.zip');});
</script></html>'''
